spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/v1/students/**

        - id: COURSE-SERVICE
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/v1/courses/**

        - id: ENROLL-SERVICE
          uri: lb://ENROLL-SERVICE
          predicates:
            - Path=/api/v1/enroll/**

        - id: INSTRUCTOR-SERVICE
          uri: lb://INSTRUCTOR-SERVICE
          predicates:
            - Path=/api/v1/instructors/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka